# AppVeyor documentation https://www.appveyor.com/docs

version: '{build}'

image:
  - Visual Studio 2017

install:
  # Download/Install OpenGL & GLFW
  - "git clone --depth 1 git://github.com/VoltanaDMG/gl-ci-helpers.git"
  - "powershell gl-ci-helpers/appveyor/install_opengl.ps1"

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

before_build:
  # Some useful debug information
  - ps: (New-Object Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/p/?LinkID=2033908', 'C:\Users\appveyor\Downloads\sdksetup.exe')
  # Execute Windows SDK
  - ps: |
      $pinfo = New-Object System.Diagnostics.ProcessStartInfo
      $pinfo.FileName = "C:\Users\appveyor\Downloads\sdksetup.exe"
      $pinfo.RedirectStandardError = $true
      $pinfo.RedirectStandardOutput = $true
      $pinfo.UseShellExecute = $false
      $pinfo.Arguments = "/q EULA=1"
      $p = New-Object System.Diagnostics.Process
      $p.StartInfo = $pinfo
      $p.Start() | Out-Null
      $p.WaitForExit()
      $p.ExitCode

build_script:
  # - ps: cd scg3
  # - ps: msbuild scg3_vc11.vcxproj /p:configuration=Release /p:platform=x64
  # - ps: dir
  
# We don't have any tests for the scg3 library
test: off
