# AppVeyor documentation https://www.appveyor.com/docs

version: '{build}'

image:
  - Visual Studio 2017

install:
  # Download/Install OpenGL & GLFW
  - "git clone --depth 1 git://github.com/VoltanaDMG/gl-ci-helpers.git"
  - "powershell gl-ci-helpers/appveyor/install_opengl.ps1"

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

before_build:
  # Donwloading Windows SDK 1809, as ISO format for offline installation
  - ps: (New-Object Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/p/?LinkID=2033686', 'C:\Users\appveyor\Downloads\winsdk.iso')
  # Unpack ISO (Windows SDK 1809)
  - mkdir C:\Users\appveyor\Downloads\WinSDK
  - ps: Invoke-Expression "& `"7z`" x C:\Users\appveyor\Downloads\winsdk.iso -y -oC:\Users\${env:UserName}\Downloads\WinSDK"
  # Execute Windows SDK
  - ps: |
      $process = start-process C:\Users\appveyor\Downloads\WinSDK\WinSDKSetup.exe -windowstyle Hidden -ArgumentList "/features + /q" -PassThru -Wait
      $process.ExitCode

build_script:
  - ps: cd scg3
  - ps: msbuild scg3_vc11.vcxproj /p:configuration=Release /p:platform=x64
  - ps: dir
  
# We don't have any tests for the scg3 library
test: off
